/*
 Generated by typeshare 1.5.0
*/

export interface Address {
	city: string;
	zipcode: string;
}

export interface Location {
	position: number[];
}

export interface Poi {
	address: Address;
	location: Location;
}

export interface User {
	my_name: string;
	my_age: number;
	address: Address;
}

export type MyEnum = 
	| { type: "MyVariant", content: boolean }
	| { type: "MyOtherVariant", content?: undefined }
	| { type: "MyNumber", content: number };

